---
title: "Exercise2: Introduction to Bioconductor, Rmarkdown and Github"
author: "Zinnera Tariq"
date: "19/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Download the data using the GEOquery Bioconductor package

```{r download data }
library(GEOquery)
data_GEO <- getGEO("GSE3606")
class(data_GEO)
names(data_GEO)
print(paste("First, I downloaded the data using getGEO(). The dataset is downloaded in a list."))
```

## A description of the study that generated the data

```{r Description}
print(paste("The purpose of the study was to investigate the effects of acute exercise on gene expression profiles of white blood cells and to identify suitable genes which may serve as surrogate markers for monitoring exercise and training load. "))
```

## Information on the experimental design used (groups, types of comparisons etc)

```{r Information}
print(paste("Five healthy male performed an exhaustive treadmill test. One week later they repeated the test at a moderate speed the same time. Blood samples were drawn before and one hour past the tests. Erythrocytes were lysed and RNA was isolated from the white blood cells. RNA was processed and hybridised on U133A 2.0 Affyetrix GeneChips. Samples were grouped and gene expression changes were detected via multiple algorithms included in GeneSpring 7.2 (Agilent).
Three groups were build from the twenty samples. All ten pre exercise samples were grouped together as the pre test group. The other two groups contained five samples related to the exhaustive test or the moderate test. TTest in combination with multiple testing corrections, principal component analysis and hierarchical clustering were used to scan for gene expression profiles induced through the different exercise conditions"))
```

## Create an ExpressionSet for the dataset

```{r ExpressionSet}
ESet_GEO <- data_GEO[[1]]
ESet <- exprs(ESet_GEO)
dim(ESet)
print(paste("To create ExpressionSet for the dataset, we use exprs(). The data has 22277 rows and 20 columns(samples)."))
```

## Top variable genes

```{r Top variable genes}
variab <- apply(ESet, 1, sd)
orderedGenes <- order(variab, decreasing=TRUE)
head(variab[order(variab, decreasing=TRUE)])
```


## Subeset of the data

```{r Subset}
smallEset <- ESet[1:15,c(1:3,18:20)]
dim(smallEset)
print(paste("I have taken a small subset of 15 rows and 6 columns"))

```

## Top variable genes of subset

```{r Top variable genes}
variab <- apply(smallEset, 1, sd)
orderedGenes <- order(variab, decreasing=TRUE)
head(variab[order(variab, decreasing=TRUE)])
```

## Plots

```{r Boxplot}
boxplot(smallEset)
boxplot(ESet)
print(paste("Almost for every observation the average of the residuals is zero. Even though, the boxplots using the whole data we have a lot of dispersions, which doesn't happen in the subset."))
```

